name: Docker images building and pushing
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  allplaywrights:
    strategy:
      matrix:
        version: [npm, pnpm, yarn]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta for Playwright executor ${{ matrix.version }}
        id: meta_playwright_executor_default
        uses: docker/metadata-action@v3
        with:
          images: kubeshop/testkube-playwright-executor
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
          flavor: |
            prefix=
            suffix=-${{ matrix.version }}

      - name: Build ${{ matrix.version }} Playwright Executor
        uses: docker/bake-action@v2
        with:
          files: |
            build/playwright-executor/docker-bake.hcl
            ${{ steps.meta_playwright_executor.outputs.bake-file }}
          targets: ${{ matrix.version }}
          push: true
